# Generated by Django 4.2.1 on 2023-05-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_categories_alter_comment_options_post_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategories',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
