# Generated by Django 4.2.1 on 2023-05-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_categories_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategories',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
